title: "TFG Alejandro Aguilera"
description: "Seguimiento del Trabajo de Fin de Grado en la URJC"
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache

author:
  name: "Alejandro Aguilera"
  avatar: "/docs/logo.png"
  bio: "Estudiante de Ingeniería de la URJC"
  location: "Madrid, España"

collections:
  progreso:
    output: true
    permalink: /progreso/:path/

defaults:
  - scope:
      path: ""
      type: progreso
    values:
      layout: single
      author_profile: false
      read_time: true

