title: TFG Alejandro Aguilera (Weblog)
description: Documentación sobre el desarrollo del Trabajo de Fin de Grado
minimal_mistakes_skin: air
search: true

markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Alejandro Aguilera"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Estudiante de la URJC trabajando en un TFG sobre análisis de patrones de uso."
  location: "Madrid, España"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/TU_USUARIO"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

